wordpress:
  restart: always
  extends:
    file: common-compose.yml
    service: wordpress
  mem_limit: 1g
  links:
    - consul:consul
    - nfs:nfs
  ports:
    - 80

mysql:
    extends:
      file: common-compose.yml
      service: mysql
    restart: always
    links:
      - consul:consul
    expose:
      - 3306

memcached:
  extends:
    file: common-compose.yml
    service: memcached
  links:
    - consul:consul
  restart: always

# Nginx as a load-balancing tier and reverse proxy
nginx:
  extends:
    file: common-compose.yml
    service: nginx
  restart: always
  ports:
  - "80"
  links:
    - consul:consul

consul:
    restart: always
    extends:
      file: common-compose.yml
      service: consul
