wordpress:
  build: .
  extends:
    file: docker-compose.yml
    service: wordpress
  links:
    - consul:consul
    - nfs:nfs
  environment:
    - CONSUL=consul
  mem_limit: 512m
  restart: never
  ports:
    - "80"

nfs:
  extends:
    file: docker-compose.yml
    service: nfs
  environment:
    - CONSUL=consul
    - CONTAINERBUDDY=file:///etc/containerbuddy.json
  links:
    - consul:consul
  ports:
    - "111"
    - "1892:1892"
    - "2049"

mysql:
  extends:
    file: docker-compose.yml
    service: mysql
  restart: never
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - CONTAINERPILOT=file:///etc/containerpilot.json
  ports:
    - "3306"

memcached:
  extends:
    file: docker-compose.yml
    service: memcached
  links:
    - consul:consul
  environment:
    - CONSUL=consul
  restart: never

# Nginx as a load-balancing tier and reverse proxy
nginx:
  extends:
    file: docker-compose.yml
    service: nginx
  ports:
  - "80:80"
  links:
    - consul:consul
  environment:
    - CONSUL=consul

consul:
  extends:
    file: docker-compose.yml
    service: consul
  restart: never
  environment:
    - CONSUL=consul
  ports:
  - "8500:8500"
